OPENAI_API_KEY = "AIzaSyDroUSXsjAYEcHt8IFRje9_Hz-BXq29VYw"
OPENAI_API_BASE = "https://generativelanguage.googleapis.com/v1beta/openai"
OPENAI_API_MODEL = "gemini-2.5-flash-preview-05-20"
SUPABASE_URL = "https://fmpilvdlktjeugbvrunv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtcGlsdmRsa3RqZXVnYnZydW52Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTExNTg0MCwiZXhwIjoyMDY0NjkxODQwfQ.BWFj1NP3qEgNKulEgFPXT2qOelejiVBgZzDMmYBNWtU"
